package oop.ex6.main.regex;

public enum Types {
    INT, DOUBLE, STRING, BOOLEAN, CHAR, POSSIBLE_VARIABLE, POSSIBLE_GLOBAL_VARIABLE_INITIALIZED,
    POSSIBLE_GLOBAL_VARIABLE_UNINITIALIZED, UNSUPPORTED_TYPE;
}
