package oop.ex6.main;

public enum LineTypesDeclare implements LineTypes{
    INT_DECLARATION_INIT_PARSER,
    DOUBLE_DECLARATION_INIT_PARSER,
    STRING_DECLARATION_INIT_PARSER,
    BOOLEAN_DECLARATION_INIT_PARSER,
    CHAR_DECLARATION_INIT_PARSER
}
