package oop.ex6.main;

public enum LineTypesAssign implements LineTypes{
    STRING_ASSIGNMENT_PARSER,
    INT_ASSIGNMENT_PARSER,
    CHAR_ASSIGNMENT_PARSER,
    BOOLEAN_ASSIGNMENT_PARSER,
    DOUBLE_ASSIGNMENT_PARSER
}
